#!/usr/bin/env bash
# ──────────────────────────────────────────────────────
# PrecisionFlow – Environment Setup Script
# Creates .env.local files from .env.example templates
# ──────────────────────────────────────────────────────
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WEB_DIR="$ROOT_DIR/apps/web"

green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }

echo ""
green "🔧 PrecisionFlow Environment Setup"
echo "──────────────────────────────────────"
echo ""

# ── Collect Supabase credentials ──
echo "Enter your Supabase credentials"
echo "(Find these at https://app.supabase.com → Project Settings → API)"
echo ""

read -rp "NEXT_PUBLIC_SUPABASE_URL: " SUPABASE_URL
read -rp "NEXT_PUBLIC_SUPABASE_ANON_KEY: " SUPABASE_ANON_KEY
read -rp "SUPABASE_SERVICE_ROLE_KEY: " SUPABASE_SERVICE_KEY

echo ""

# ── Collect Gemini API key (optional) ──
echo "Enter your Google Gemini API key (optional, press Enter to skip)"
echo "(Get one at https://aistudio.google.com/app/apikey)"
echo ""

read -rp "GEMINI_API_KEY: " GEMINI_KEY

echo ""

# ── Generate the env file content ──
generate_env() {
  cat << EOF
# PrecisionFlow - Local Environment
# Generated by scripts/setup-env.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# ──────────────────────────────────────────────────────

# ── Supabase ──
NEXT_PUBLIC_SUPABASE_URL=${SUPABASE_URL}
NEXT_PUBLIC_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_KEY}

# ── Google Gemini AI ──
GEMINI_API_KEY=${GEMINI_KEY:-your-gemini-api-key-here}

# ── App URLs ──
NEXT_PUBLIC_APP_URL=http://localhost:3000

# ── Feature Flags ──
NEXT_PUBLIC_ENABLE_AI=$([ -n "${GEMINI_KEY}" ] && echo true || echo false)
NEXT_PUBLIC_ENABLE_ANALYTICS=false
EOF
}

# ── Write root .env.local ──
ENV_CONTENT="$(generate_env)"

if [ -f "$ROOT_DIR/.env.local" ]; then
  yellow "⚠  $ROOT_DIR/.env.local already exists."
  read -rp "   Overwrite? (y/N): " overwrite
  if [[ "$overwrite" =~ ^[Yy]$ ]]; then
    echo "$ENV_CONTENT" > "$ROOT_DIR/.env.local"
    green "   ✓ Root .env.local updated"
  else
    yellow "   → Skipped"
  fi
else
  echo "$ENV_CONTENT" > "$ROOT_DIR/.env.local"
  green "   ✓ Root .env.local created"
fi

# ── Write web app .env.local ──
if [ -f "$WEB_DIR/.env.local" ]; then
  yellow "⚠  $WEB_DIR/.env.local already exists."
  read -rp "   Overwrite? (y/N): " overwrite
  if [[ "$overwrite" =~ ^[Yy]$ ]]; then
    echo "$ENV_CONTENT" > "$WEB_DIR/.env.local"
    green "   ✓ Web app .env.local updated"
  else
    yellow "   → Skipped"
  fi
else
  echo "$ENV_CONTENT" > "$WEB_DIR/.env.local"
  green "   ✓ Web app .env.local created"
fi

echo ""
green "✅ Environment setup complete!"
echo ""
echo "Next steps:"
echo "  1. pnpm install       # Install dependencies"
echo "  2. pnpm dev:web       # Start development server"
echo "  3. Open http://localhost:3000"
echo ""
