/**
 * Database types placeholder
 * This file will be auto-generated by Supabase CLI
 * Run: pnpm db:generate
 */

export type Database = {
  public: {
    Tables: Record<string, never>;
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
};
